/**
 * Mr. Mags — license manager
 *
 * Three states:
 *   active_trial   — within 7-day trial window
 *   expired_trial  — trial over, no key
 *   licensed       — valid MMAGS-PERP- key on file
 *
 * Key format: MMAGS-PERP-<32 alphanum chars>
 * Validation: format check + HMAC verify against LICENSE_HMAC_SECRET
 *   (same secret as the CF Pages purchase function).
 *
 * Trial start: recorded in <userData>/license.json on first launch.
 * License key: stored in same file after activation.
 *
 * Teacher / free licenses use prefix MMAGS-FREE- and never expire.
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const TRIAL_DAYS = 7;
const KEY_RE = /^MMAGS-(PERP|FREE)-[A-Z0-9]{32}$/;

// Shared with CF Pages purchase.js + teachers/verify.js
// Injected at build time via electron-builder extraMetadata, or read from
// env var in development. In production the value is baked into the binary
// via the build-time replacement below.
const HMAC_SECRET = process.env.MRMAGS_LICENSE_SECRET || '__MRMAGS_LICENSE_SECRET__';

class LicenseManager {
  constructor(userData) {
    this.file = path.join(userData, 'license.json');
    this._data = this._load();
  }

  _load() {
    try {
      if (fs.existsSync(this.file)) {
        return JSON.parse(fs.readFileSync(this.file, 'utf8'));
      }
    } catch {}
    return {};
  }

  _save() {
    try {
      const tmp = this.file + '.tmp';
      fs.writeFileSync(tmp, JSON.stringify(this._data, null, 2), 'utf8');
      fs.renameSync(tmp, this.file);
    } catch (e) {
      console.error('[license] save failed', e.message);
    }
  }

  // Call once on first app launch. Idempotent.
  ensureTrialStart() {
    if (!this._data.trial_started_at) {
      this._data.trial_started_at = new Date().toISOString();
      this._save();
    }
  }

  trialDaysRemaining() {
    if (!this._data.trial_started_at) return TRIAL_DAYS;
    const start = new Date(this._data.trial_started_at).getTime();
    const elapsed = (Date.now() - start) / (1000 * 60 * 60 * 24);
    return Math.max(0, Math.ceil(TRIAL_DAYS - elapsed));
  }

  isTrialActive() {
    return this.trialDaysRemaining() > 0;
  }

  isLicensed() {
    return !!(this._data.license_key && KEY_RE.test(this._data.license_key));
  }

  // Returns: 'licensed' | 'active_trial' | 'expired_trial'
  status() {
    if (this.isLicensed()) return 'licensed';
    if (this.isTrialActive()) return 'active_trial';
    return 'expired_trial';
  }

  // Returns { ok, error } — validates format, then verifies HMAC token embedded in key
  activate(key) {
    const k = (key || '').trim().toUpperCase();

    if (!KEY_RE.test(k)) {
      return { ok: false, error: 'Invalid key format. Keys look like: MMAGS-PERP-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' };
    }

    // HMAC validation: the token portion of the key was generated by
    // signLicense() in _shared.js. The key is MMAGS-TYPE-<uppercase hex of
    // first 32 chars of the base64url HMAC token>. We can't re-derive the
    // full payload here, but we can verify the token isn't random garbage by
    // checking it against a list of valid prefixes signed with our secret.
    // For offline validation we use a simpler check: the key must pass the
    // format regex AND a MAC of the key itself must match a stored receipt.
    //
    // Simpler approach that works offline:
    // The purchase function stores license_key in D1. We don't query D1
    // here (offline-first). Instead we verify the key was signed by us:
    // the last 8 chars of the token are HMAC-SHA256(key, secret)[0..3] as hex.
    // This lets the app verify offline without a server roundtrip.
    //
    // For FREE keys (teacher licenses), skip HMAC — just accept the format.
    if (k.startsWith('MMAGS-FREE-')) {
      this._data.license_key = k;
      this._data.activated_at = new Date().toISOString();
      this._save();
      return { ok: true };
    }

    // PERP key: last 8 chars = first 4 bytes of HMAC-SHA256(first 24 chars, secret)
    const token = k.slice(11); // strip "MMAGS-PERP-"
    const payload = token.slice(0, 24);
    const claimed_mac = token.slice(24).toLowerCase();

    try {
      const computed = crypto.createHmac('sha256', HMAC_SECRET)
        .update(payload)
        .digest('hex')
        .slice(0, 8);

      if (computed !== claimed_mac) {
        return { ok: false, error: 'Key not recognized. Double-check it was copied completely, or email hello@mrmags.org.' };
      }
    } catch {
      // If secret placeholder wasn't replaced at build time, skip HMAC check
      // and accept any validly-formatted key. Development fallback only.
      if (HMAC_SECRET === '__MRMAGS_LICENSE_SECRET__') {
        // dev build — accept format-valid keys without HMAC
      } else {
        return { ok: false, error: 'License validation error. Try again or email hello@mrmags.org.' };
      }
    }

    this._data.license_key = k;
    this._data.activated_at = new Date().toISOString();
    this._save();
    return { ok: true };
  }

  licenseKey() {
    return this._data.license_key || null;
  }

  activatedAt() {
    return this._data.activated_at || null;
  }

  trialStartedAt() {
    return this._data.trial_started_at || null;
  }
}

module.exports = LicenseManager;
